"""initial models

Revision ID: 2dd240c697f
Revises: None
Create Date: 2014-03-16 21:26:46.733150

"""

# revision identifiers, used by Alembic.
revision = '2dd240c697f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('username', sa.Unicode(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('userprofiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('given_name', sa.Unicode(length=255), nullable=True),
    sa.Column('family_name', sa.Unicode(length=255), nullable=True),
    sa.Column('nick', sa.Unicode(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True),
    sa.Column('plan', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userprofileimages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['userprofiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userprofileimages')
    op.drop_table('userprofiles')
    op.drop_table('users')
    ### end Alembic commands ###
